apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{.Values.name}}
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
spec:
  progressDeadlineSeconds: 600
{{- if eq .Values.namespace "prod" }}
  replicas: 3
{{- end }}
{{- if eq .Values.namespace "dev" }}
  replicas: 1
{{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{.Values.name}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "{{.Values.name}}"
    spec:
      containers:
      - image: "{{.Values.petclinic.imageName}}:{{.Values.petclinic.imageTag}}"
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: "mysql-pass-{{ .Values.namespace }}"
          - name: MYSQL_DATABASE
            value: "mysql"
        imagePullPolicy: Always
        name: "{{.Values.name}}"
        ports:
        - containerPort: {{ .Values.petclinic.port }}
          protocol: TCP
        resources:
          requests:
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: {{.Values.name}}
      serviceAccountName: {{.Values.name}}
      terminationGracePeriodSeconds: 30
