apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "{{.Values.name}}.keycloak.k8s-cdp-cluster.tk"
      http:
        paths:
          - path: /
            backend:
              serviceName: {{.Values.name}}
              servicePort: {{.Values.petclinic.port}}
