apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
  {{- template "mysql.labels" }}
spec:
  selector:
    app: {{.Values.name}}
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.petclinic.port }}
      targetPort: {{.Values.petclinic.port}}
      protocol: TCP
