apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}-configmap
  namespace: {{.Values.namespace}}
  {{- template "mysql.labels" }}
data:
  my.cnf: |-
    {{ .Files.Get "./my.cnf" }}
