apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{.Values.mysql.name}}
  name: {{.Values.mysql.secretName}}-{{.Values.namespace}}
  namespace: {{.Values.namespace}}
type: Opaque
data:
  password: {{.Values.mysql.password | b64enc | quote }}
